### ISSUE TITLE
This project looks amazing

### ISSUE THREAD

**Issue by crdoconnor** [Predeactor/Fabricius#12]
Just a drive by compliment. I think it's a shame, but I understand that you had to stop working on it.

The design and philosophy precisely matched what I was looking for. I was looking to build a project template and I was thinking it would be nice if there was something out there that was strongly typed that I could use. It's rare that I conceptualize a project I would like to exist and then I find somebody has gone and built it.

**Comment by madebylydia** [comment]
Thank you very much for your sincere comment!

As I pursue my studies, I am not really in position to keep the enjoyment of working on my few personal projects. Fabricius feels like a lot more work than I originally thought it was, so I kindly stop for the moment being.
Hopefully, one day, there'll be light, and I might be able to keep it up!

Thank you for your comment, enjoy your day :)

**Comment by madebylydia** [comment]
Hey!

Hope #13 will make your little Christmas gift! :) 

Merry Christmas and happy new year!
